name: Loophole Tunnel
version: "1.0.6"
stage: stable
slug: ha-loophole-addon
description: Home Assistant app for loophole.cloud tunneling to expose your HA instance with HTTPS over the public internet.
url: https://github.com/dasflaigsi/ha-supervisor-apps
arch:
  - amd64
  - aarch64
init: false
startup: services
boot: auto
homeassistant_api: true
options:
  port: 8123
  hostname: ""
  verbose: false
schema:
  port: int(1,65535)
  hostname: str
  verbose: bool
